import todo from "@/components/assets/Todo.png";
import shoeStore from "@/components/assets/shoeStore.png";
import snapgram from "@/components/assets/snapgram.png";
import portfolio from "@/components/assets/portfolio.png";
import mail from "@/components/assets/mail.png";

export const projectData = [
  {
    img: shoeStore,
    title: "Shoes Store",
    githubLink: "https://github.com/deshwaninikil/shoes-store.git",
    deployedLink: "https://xshoes-store.netlify.app/",
    skill: ["ReactJs", "CSS", "Auth"],
    description:
      "Discover the world's finest footwear at our premier e-commerce site, offering an extensive selection of shoes for every taste and occasion. Whether you're searching for stylish heels, comfortable sneakers, elegant dress shoes, or durable boots, we have it all. Our curated collection features top brands and the latest trends, ensuring you find the perfect pair to complement your style. Enjoy a seamless shopping experience with detailed product descriptions, high-quality images, and customer reviews. Plus, take advantage of our competitive prices and special offers. Step into a world of comfort and style with our exceptional shoe collection today.",
  },
  {
    img: snapgram,
    title: "Snapgram",
    githubLink: "https://github.com/deshwaninikil/snap-gram.git",
    deployedLink: "https://xsnap-gram.netlify.app/login",
    skill: ["ReactJS", "Tailwind CSS", "Auth"],
    description:
      "Snapgram is a dynamic social media web app built with React.js, designed to connect people through engaging and interactive features. Share photos, videos, and stories with friends and followers, and discover new content from users worldwide. The app offers a seamless and responsive user experience, with real-time updates and intuitive navigation. Customize your profile, explore trending topics, and join vibrant communities. Snapgram also prioritizes security and privacy, ensuring a safe environment for all users. With regular updates and new features, Snapgram continually enhances its platform to keep you connected and entertained. Join Snapgram today and be part of a global social network.",
  },
  {
    img: portfolio,
    title: "Portfolio Website",
    githubLink: "https://github.com/deshwaninikil/portfolio-next.git",
    deployedLink: "",
    skill: ["NextJs", "Tailwind CSS"],
    description:
      "Welcome to my portfolio website built with Next.js and styled using Tailwind CSS. As a showcase of my skills and projects, this platform reflects my passion for clean design and efficient development. ",
  },

  {
    img: todo,
    title: "Full Stack Todo App",
    githubLink: "https://github.com/deshwaninikil/todo_app.git",
    deployedLink: "https://xtodo-app.netlify.app",
    skill: ["NextJs", "CSS", "NextJs Backend", "PostgreSQL"],
    description:
      "A MERN Stack Task Management Application Capable of performing CRUD based Operations and handle requests generated by the User.",
  },
  {
    img: mail,
    title: "Mail App",
    githubLink: "https://github.com/deshwaninikil/mail-app.git",
    deployedLink: "https://xmail-app.netlify.app",
    skill: ["ReactJs", "CSS", "Auth"],
    description:
      "Developed a Mail App using ReactJS and CSS, enabling efficient email management. The app features a responsive and intuitive user interface for viewing and organizing emails, including an inbox with filters for unread and starred emails. Users can easily mark emails as read, report spam, and delete emails, providing full control over their inbox. This ensures an organized and streamlined email management experience. The implementation of these features highlights the app's focus on usability and efficiency, making it a robust solution for daily email handling.",
  },
];
